### ISSUE TITLE
first issue

### ISSUE THREAD

**Issue by focussing** [el-jacko/vue-editortable#4]
Hi! I would like to test your table, but first some questions before I will start to implement it:

1) can I just give in an array of rows, so do the database actions myself
2) the database api is [this](https://github.com/alixaxel/ArrestDB) so it needs different verbs for the CRUD actions. will that work?
3) I would like to use FontAwesome icons in rows / columns header, how do I do that
4) what events can I catch in Vue? Like DeleteRow and RowEdited or so?
5) How can I style the table

**Comment by el-jacko** [comment]
Hi,

> can I just give in an array of rows, so do the database actions myself

yes, you can pass your data as the values prop.

> the database api is this so it needs different verbs for the CRUD actions. will that work?

The only difference i see is that it uses PUT instead of PATCH. I could implement both if needed.

> I would like to use FontAwesome icons in rows / columns header, how do I do that

The component uses the vue-awesome component, which uses the font-awesome icons. Only the needed icons are included. There is no possibility to add different icons.

> what events can I catch in Vue? Like DeleteRow and RowEdited or so?

This is something i want to implement in the future.

> How can I style the table

You can chose between the custom dark styling or the vuetify styling. It needs to be defined and passed as the styling prop. -> [more informations](https://github.com/el-jacko/vue-editortable/wiki/3.-Configuration). Or you can simply override the css styles.
